name: "Meow Maker for Catppuccin"
author: "grokdesigns"
description: "Action to run whiskers on uploaded Tera files and automatically output templates to repo."
branding:
  icon: "copy"
  color: "gray-dark"

inputs:
  git_username:
    description: "Git username for commits"
    required: true
    default: "github-actions[bot]"
  git_email:
    description: "Git email for commits"
    required: true
    default: "github-actions[bot]@users.noreply.github.com"
  skip_ci:
    description: "Whether to add [no ci] to commit messages"
    required: true
    default: "yes"
  commit_message:
    description: "Commit message for generated files"
    required: true
    default: "🐱 - Generated via Meow Maker"
  output_folder:
    description: "Folder to output generated files"
    required: true
    default: "output"
  input_folder:
    description: "Folder containing template files"
    required: true
    default: "templates"

runs:
  using: "docker"
  image: "grokdesigns/meow-maker:latest"
